name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FactChecker
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.9'
      - name: Build with Gradle
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DB_URL_TEST: ${{ secrets.DB_URL_TEST}}
          DB_USER_TEST: ${{ secrets.DB_USER_TEST}}
          DB_PASS_TEST: ${{ secrets.DB_PASS_TEST}}
        run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FactChecker
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DB_URL_TEST: ${{ secrets.DB_URL_TEST}}
          DB_USER_TEST: ${{ secrets.DB_USER_TEST}}
          DB_PASS_TEST: ${{ secrets.DB_PASS_TEST}}
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          gradle-version: '8.9'
          build-root-directory: ./FactChecker
